blank_issues_enabled: false
contact_links:
  - name: 🗣️ Discord Support
    url: https://discord.com/users/1236578850255933450
    about: Ask help!
  - name: 📷 Instagram Support
    url: https://www.instagram.com/stefa.ceriani/
    about: 1️⃣ Semd me a message 2️⃣ Wait 24h  |  In the message specificate for "ChromaShift..."
